### ISSUE TITLE
Docbook source fail to build

### ISSUE THREAD

**Issue by zoglesby** [projectmallard/pintail#13]
When using pintail to build docbook source the following error occurs. 

> Traceback (most recent call last):
>   File "/usr/bin/pintail", line 4, in <module>
>     **import**('pkg_resources').run_script('pintail==0.1', 'pintail')
>   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 735, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 1659, in run_script
>     exec(script_code, namespace, namespace)
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/EGG-INFO/scripts/pintail", line 100, in <module>
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/core.py", line 621, in build
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/core.py", line 684, in build_html
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/core.py", line 403, in build_html
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/core.py", line 408, in build_html
>   File "/usr/lib/python3.4/site-packages/pintail-0.1-py3.4.egg/pintail/docbook.py", line 127, in build_html
> AttributeError: 'DocBookPage' object has no attribute 'db2html'

**Comment by zoglesby** [comment]
That was while building https://git.fedorahosted.org/cgit/docs/release-notes.git/log/?h=f23 and the relevant part of the pintail.cfg is 

> [/release-notes/]
> git_repository = ssh://git.fedorahosted.org/git/docs/release-notes.git
> git_branch = f23
> git_directory = en-US/
> docbook = Release_Notes.xml
