### ISSUE TITLE
ISOamsc not loading - could be a chained loading issue

### ISSUE THREAD

**Issue by bexelbie** [projectmallard/pintail#20]
I was able to square away all of the issues with the Fedora Installation Guide, but this one.  This appears to be indirectly referenced.  Is this a known issue?

```
http://www.oasis-open.org/docbook/xml/4.5/dbcentx.mod:316: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/ent/isoamsc.ent"
%ISOamsc;
         ^
Entity: line 1: 
 %ISOamsc; 
          ^
Traceback (most recent call last):
  File "/usr/bin/pintail", line 103, in <module>
    site.build()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 536, in build
    self.read_directories()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 500, in read_directories
    self.root = Directory(self, '/')
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 201, in __init__
    self.read_directories()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 238, in read_directories
    subdir = Directory(self.site, subpath, parent=self)
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 202, in __init__
    self.read_pages()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 258, in read_pages
    page.page_id)
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by bexelbie** [comment]
Closing - really #24
