### ISSUE TITLE
XML Fallback not implemented?

### ISSUE THREAD

**Issue by bexelbie** [projectmallard/pintail#22]
This is possibly related to #20 

This error:

```
/workdir/__pintail__/git/https%3A!!pagure.io!bex-install-guide-test.git@@master/en-US/Preface.xml:9: element include: XInclude error : could not load /workdir/__pintail__/git/https%3A!!pagure.io!bex-install-guide-test.git@@master/en-US/Feedback.xml, and no fallback was found
```

seems to be caused by this XML

```
    <xi:include href="Feedback.xml" xmlns:xi="http://www.w3.org/2001/XInclude"> <xi:fallback xmlns:xi="http://www.w3.org/2001/XInclude"> <xi:include href="Common_Content/Feedback.xml" xmlns:xi="http://www.w3.org/2001/XInclude" />

```

There is no Feedback.xml in the directory so the fallback should be used.

**Comment by bexelbie** [comment]
Slightly different error received after futzing a bit:

```
warning: failed to load external entity "/workdir/__pintail__/git/https%3A!!pagure.io!bex-install-guide-test.git@@master/en-US/Feedback.xml"

Traceback (most recent call last):
  File "/usr/bin/pintail", line 103, in <module>
    site.build()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 536, in build
    self.read_directories()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 511, in read_directories
    directory = cls(self, path)
  File "/usr/lib/python3.5/site-packages/pintail/git.py", line 48, in __init__
    super().__init__(site, path, parent=parent)
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 202, in __init__
    self.read_pages()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 258, in read_pages
    page.page_id)
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by bexelbie** [comment]
Closing and replacing with #24
