### ISSUE TITLE
TypeError: Can't convert 'NoneType' object to str implicitly with DocBook

### ISSUE THREAD

**Issue by bexelbie** [projectmallard/pintail#24]
```
Traceback (most recent call last):
  File "/usr/bin/pintail", line 103, in <module>
    site.build()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 536, in build
    self.read_directories()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 500, in read_directories
    self.root = Directory(self, '/')
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 201, in __init__
    self.read_directories()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 238, in read_directories
    subdir = Directory(self.site, subpath, parent=self)
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 202, in __init__
    self.read_pages()
  File "/usr/lib/python3.5/site-packages/pintail/site.py", line 258, in read_pages
    page.page_id)
TypeError: Can't convert 'NoneType' object to str implicitly
```

Test Repo: ssh://git@pagure.io/bex-install-guide-test.git

**Comment by shaunix** [comment]
This is actually an issue of chunked elements not having id (or xml:id) attributes. I've just added code to automatically assign those attributes, since DocBook doesn't technically require them. The XInclude warning in issue #22 is a red herring. libxml2 handles the fallback fine, but it will always warn you about it.
